Repository spring-cloud/spring-cloud-config, pull requests merged in 2018-10, with the labels that each got.

#1162 Adds failure analyzer for git uri error
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/diagnostics/GitUriFailureAnalyzer.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/main/resources/META-INF/spring.factories
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/NativeBootstrapFailureAnalyzerTests.java
  spring-cloud-config-server/src/test/resources/enable-nativebootstrap.yml
Labels: in progress

#1164 Fix spelling mistake.
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: waiting-for-triage

#1170 Fix wrong synchronization on Spring Refresh Context Event (#1168)
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryConcurrencyTests.java
Labels: bug
