Repository spring-cloud/spring-cloud-config, pull requests merged in 2018-11, with the labels that each got.

#1179 Bumping jgit to 5.1.3.201810200350-r
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryTests.java
Labels: enhancement, in progress

#1178 Fix GitCredentialsProviderFactory
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/GitCredentialsProviderFactory.java
Labels: waiting-for-triage

#1183 Fix error in documentation
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: waiting-for-triage

#1182 Fix spelling mistake
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: waiting-for-triage

#1185 Override native default label if config server default label is not null
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepositoryFactoryTest.java
Labels: in progress

#1188 Make 'JGitEnvironmentRepository.JGitFactory' public
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
Labels: enhancement

#1198 Fix error in fail-fast doc
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: waiting-for-triage
