Repository spring-cloud/spring-cloud-config, pull requests merged in 2019-12, with the labels that each got.

#1518 Added support for trusted certificates
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/HttpClientConfigurableHttpConnectionFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/encryption/EncryptionIntegrationTests.java
  spring-cloud-config-server/src/test/resources/server.jks
Labels: enhancement

#1521 Typo: Decrpyting -> Decrypting
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: waiting-for-triage

#1517 Add Resource API support to AWS S3 EnvironmentRepository
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepositoryTests.java
Labels: in progress

#1522 Migrate VaultEnvironmentRepository from RestTemplate to Spring Vault.
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-server/.flattened-pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractVaultEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryFactoryTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryTests.java
Labels: in progress

#1524 Documenting changes that resulted from issue 1475
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: documentation

#1525 Documenting changes that resulted from issue 1506
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: documentation

#1526 Add support for additional Vault authentication methods.
  pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultClientConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultClientConfigurationTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryFactoryTests.java
Labels: in progress

#1527 Refactor Spring Vault authentication into decomposed classes.
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/VaultConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultClientConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/AppRoleClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/AwsEc2ClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/AwsIamClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/AzureMsiClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/CertificateClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/CubbyholeClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/GcpGceClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/GcpIamClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/KubernetesClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/PcfClientAuthenticationProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/TokenClientAuthenticationProvider.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultClientConfigurationTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/authentication/AppRoleClientAuthenticationProviderTests.java
Labels: in progress
