Repository spring-cloud/spring-cloud-config, pull requests merged in 2019-06, with the labels that each got.

#1398 Add abstraction for retrieving config token.
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/VaultConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/ConfigTokenProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentConfigTokenProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/HttpRequestConfigTokenProvider.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/HttpRequestConfigTokenProviderTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepositoryIntegrationTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepositoryTests.java
Labels: waiting-for-triage

#1406 Fixes #1403 - add connect time out setting for config client
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocatorTests.java
Labels: enhancement

#1405 fix svnKitEnvironmentRepository param order
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
Labels: waiting-for-triage

#1385 Allow file:// URLs for file monitoring in git profile
  spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/FileMonitorConfiguration.java
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/FileMonitorConfigurationTest.java
Labels: waiting for feedback

#1410 Replace string concatenation
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java
Labels: enhancement
