Repository spring-cloud/spring-cloud-config, pull requests merged in 2019-02, with the labels that each got.

#1246 Add support for SSH proxy (HTTP)
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactoryTest.java
Labels: in progress

#1235 Support If-Modified-Since
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/resource/ResourceControllerTests.java
Labels: in progress

#1247 #1239 allow multiple repos in FileMonitorConfiguration.
  spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/FileMonitorConfiguration.java
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/FileMonitorConfigurationTest.java
Labels: waiting-for-triage

#1180 Dont use parent of basedir when using a parameterized url
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MultipleJGitEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/MultipleJGitEnvironmentRepositoryTests.java
Labels: in progress

#1250 documented value of config.fail-fast value for retry is incorrect
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: documentation

#1258 Use jks as the default KeyStore type
  docs/src/main/asciidoc/spring-cloud-config.adoc
  pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EncryptionAutoConfiguration.java
Labels: in progress
