Repository spring-cloud/spring-cloud-config, pull requests merged in 2019-03, with the labels that each got.

#1271 Remove unused declaration
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
Labels: task

#1280 URL Cleanup
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
Labels: waiting-for-triage

#1292 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
Labels: waiting-for-triage

#1291 URL Cleanup
  1.1.x/ghpages.sh
  1.3.x/ghpages.sh
  1.4.x/ghpages.sh
  2.0.x/ghpages.sh
  2.1.x/ghpages.sh
  ghpages.sh
Labels: waiting-for-triage

#1289 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
Labels: waiting-for-triage

#1288 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
Labels: waiting-for-triage

#1287 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
Labels: waiting-for-triage

#1286 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
Labels: waiting-for-triage

#1285 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
Labels: waiting-for-triage

#1282 Support for Redis backend repository
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/RedisEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/RedisEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/RedisEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/CompositeClasspathTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/RedisEnvironmentRepositoryIntegrationTests.java
Labels: enhancement, feedback-provided

#1335 URL Cleanup
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GitlabPropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/resources/gitlab.json
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SvnKitEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AwsCodeCommitCredentialProvider.java
  spring-cloud-config-server/src/test/resources/svn-config-repo/README.txt
  spring-cloud-config-server/src/test/resources/svn-config-repo/conf/svnserve.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/db/fsfs.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/start-commit.tmpl
Labels: waiting-for-triage

#1333 URL Cleanup
  .editorconfig
  .github/CONTRIBUTING.md
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GiteePropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GitlabPropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/resources/pathsamples/gitea.json
  spring-cloud-config-monitor/src/test/resources/pathsamples/gitee.json
  spring-cloud-config-monitor/src/test/resources/pathsamples/gitlab.json
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SvnKitEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AwsCodeCommitCredentialProvider.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/config/HttpClientVaultRestTemplateFactoryTest.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/ConfigurableHttpConnectionFactoryIntegrationTests.java
  spring-cloud-config-server/src/test/resources/svn-config-repo/README.txt
  spring-cloud-config-server/src/test/resources/svn-config-repo/conf/svnserve.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/db/fsfs.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/start-commit.tmpl
Labels: waiting-for-triage

#1332 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GiteePropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GitlabPropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/resources/gitea.json
  spring-cloud-config-monitor/src/test/resources/gitee.json
  spring-cloud-config-monitor/src/test/resources/gitlab.json
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SvnKitEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AwsCodeCommitCredentialProvider.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/config/HttpClientVaultRestTemplateFactoryTest.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/ConfigurableHttpConnectionFactoryIntegrationTests.java
  spring-cloud-config-server/src/test/resources/svn-config-repo/README.txt
  spring-cloud-config-server/src/test/resources/svn-config-repo/conf/svnserve.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/db/fsfs.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/start-commit.tmpl
Labels: waiting-for-triage

#1331 URL Cleanup
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GitlabPropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/resources/gitlab.json
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SvnKitEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AwsCodeCommitCredentialProvider.java
  spring-cloud-config-server/src/test/resources/svn-config-repo/README.txt
  spring-cloud-config-server/src/test/resources/svn-config-repo/conf/svnserve.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/db/fsfs.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/start-commit.tmpl
Labels: waiting-for-triage

#1330 URL Cleanup
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GitlabPropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/resources/gitlab.json
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SvnKitEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AwsCodeCommitCredentialProvider.java
  spring-cloud-config-server/src/test/resources/svn-config-repo/README.txt
  spring-cloud-config-server/src/test/resources/svn-config-repo/conf/svnserve.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/db/fsfs.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/start-commit.tmpl
Labels: waiting-for-triage

#1329 URL Cleanup
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GitlabPropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/resources/gitlab.json
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SvnKitEnvironmentRepository.java
  spring-cloud-config-server/src/test/resources/svn-config-repo/README.txt
  spring-cloud-config-server/src/test/resources/svn-config-repo/conf/svnserve.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/db/fsfs.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/start-commit.tmpl
Labels: waiting-for-triage

#1325 URL Cleanup
  docs/pom.xml
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
  src/checkstyle/checkstyle-suppressions.xml
Labels: waiting-for-triage

#1328 URL Cleanup
  README.adoc
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/GitlabPropertyPathNotificationExtractorTests.java
  spring-cloud-config-monitor/src/test/resources/gitlab.json
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SvnKitEnvironmentRepository.java
  spring-cloud-config-server/src/test/resources/svn-config-repo/README.txt
  spring-cloud-config-server/src/test/resources/svn-config-repo/conf/svnserve.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/db/fsfs.conf
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/post-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-commit.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/pre-revprop-change.tmpl
  spring-cloud-config-server/src/test/resources/svn-config-repo/hooks/start-commit.tmpl
Labels: waiting-for-triage

#1327 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#1324 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#1323 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#1322 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#1321 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#1320 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#1306 URL Cleanup
  bootstrap/css/bootstrap-responsive.css
  bootstrap/css/bootstrap-responsive.min.css
  bootstrap/css/bootstrap.css
  bootstrap/css/bootstrap.min.css
  bootstrap/js/bootstrap.js
  bootstrap/js/bootstrap.min.js
Labels: waiting-for-triage

#1299 URL Cleanup
  docs/pom.xml
  pom.xml
  spring-cloud-config-client/pom.xml
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-monitor/pom.xml
  spring-cloud-config-sample/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-starter-config/pom.xml
  src/checkstyle/checkstyle-suppressions.xml
Labels: waiting-for-triage
