Repository spring-cloud/spring-cloud-config, pull requests merged in 2021-01, with the labels that each got.

#1726 Add support for multiple application config in aws s3 repository.
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepositoryTests.java
Labels: enhancement

#1610 Use default label if cloneOnStart is true
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryTests.java
Labels: enhancement

#1593 Add index regen if config server has force-pull
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryTests.java
Labels: enhancement

#1719 Update AWS CodeCommit repo pattern
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: documentation

#1713 CF Auth issue with Instance certificate issue expiry for 2.2.x
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/authentication/PcfClientAuthenticationProvider.java
Labels: in progress

#1716 remove redundanct default search location
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AbstractScmAccessor.java
Labels: bug

#1678 Server-side resolve Vault secrets inside application's property sources
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerMvcConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/VaultEncryptionAutoConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/vault/VaultEnvironmentEncryptor.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentEncryptorEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepository.java
  spring-cloud-config-server/src/main/resources/META-INF/spring.factories
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/encryption/vault/VaultEnvironmentEncryptorTests.java
Labels: enhancement
