Repository spring-cloud/spring-cloud-config, pull requests merged in 2021-03, with the labels that each got.

#1815 fix documentation bug
  docs/src/main/asciidoc/quickstart.adoc
Labels: waiting-for-triage

#1810 Add Spring Boot config data import to quiskstart.
  README.adoc
  docs/src/main/asciidoc/quickstart.adoc
Labels: documentation

#1821 Remove if else
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
Labels: task

#1817 Add api examples
  docs/src/main/asciidoc/quickstart.adoc
Labels: documentation

#1832 Get all property sources for health indicator
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerHealthIndicator.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerHealthIndicatorTests.java
Labels: bug

#1837 Adding logging when we fail to get the Environment
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/VanillaConfigServerIntegrationTests.java
  spring-cloud-config-server/src/test/resources/config-repo/invalid.yaml
Labels: enhancement

#1842 bump spring vault core to 2.3.2 to be compatible with spring cloud vault
  spring-cloud-config-dependencies/pom.xml
Labels: in progress

#1844 Use optional in classpath search location
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/GenericResourceRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/NativeConfigServerIntegrationTests.java
  spring-cloud-config-server/src/test/resources/config/configserver.yaml
  spring-cloud-config-server/src/test/resources/configserver.yaml
Labels: in progress

#1853 Take into account config data in list format
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataMissingEnvironmentPostProcessor.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataMissingEnvironmentPostProcessorTests.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataNoImportIntegrationTests.java
Labels: bug
