Repository spring-cloud/spring-cloud-config, pull requests merged in 2021-07, with the labels that each got.

#1926 Make GitCredentialsProviderFactory a bean
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MultipleJGitEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfigurationTests.java
Labels: in progress

#1927 refactor: remove `@RequestMapping` annotations
  spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java
  spring-cloud-config-sample/src/main/java/sample/Application.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java
Labels: task

#1931 Use ConfigClientProperties if it exists in the BootstrapContext
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolver.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java
Labels: in progress

#1638 Integration with AWS Secrets Manager
  docs/src/main/asciidoc/spring-cloud-config.adoc
  pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentRepositoryTests.java
Labels: enhancement, in progress

#1833 Feature(Vault KV2): to support a path after mount-path (backend) under which the key(s)/application(s) be found
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultKvAccessStrategyFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/VaultKvAccessStrategyFactoryTest.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/VaultKvAccessStrategyTest.java
Labels: enhancement

#1588 Deterministic failure/warning with application- prefixed names
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/diagnostics/analyzer/InvalidApplicationNameExceptionFailureAnalyzer.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/validation/InvalidApplicationNameException.java
  spring-cloud-config-client/src/main/resources/META-INF/spring.factories
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigClientAutoConfigurationTests.java
Labels: in progress
