Repository spring-cloud/spring-cloud-config, pull requests merged in 2021-11, with the labels that each got.

#1990 Fix spring.config.import for environment type native
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/NativeEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/resources/import.yml
  spring-cloud-config-server/src/test/resources/test/import.yml
  spring-cloud-config-server/src/test/resources/test/import/foo.yml
Labels: waiting for feedback

#1971 Modified usage of Redis containers for tests
  .circleci/config.yml
  pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/RedisEnvironmentRepositoryIntegrationTests.java
Labels: waiting-for-triage

#1999 Modified usage of cache for CircleCI
  .circleci/config.yml
Labels: task

#2000 Run Docker tests in CircleCI
  .circleci/config.yml
Labels: task

#1998 Moves default label to main with fallback to master
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MultipleJGitEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryIntegrationTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/MultipleJGitEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/resources/encrypt-repo/git/HEAD
  spring-cloud-config-server/src/test/resources/encrypt-repo/git/index
  spring-cloud-config-server/src/test/resources/encrypt-repo/git/logs/HEAD
  spring-cloud-config-server/src/test/resources/encrypt-repo/git/logs/refs/heads/main
  spring-cloud-config-server/src/test/resources/encrypt-repo/git/logs/refs/heads/master
  spring-cloud-config-server/src/test/resources/encrypt-repo/git/refs/heads/main
Labels: enhancement
