Repository spring-cloud/spring-cloud-config, pull requests merged in 2022-10, with the labels that each got.

#2173 Simlify encryption config for aot
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/DefaultTextEncryptionAutoConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EncryptionAutoConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/RsaEncryptionAutoConfiguration.java
  spring-cloud-config-server/src/main/resources/META-INF/spring.factories
  spring-cloud-config-server/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: task

#2174 Config client hints
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientAutoConfiguration.java
  spring-cloud-config-client/src/main/resources/META-INF/spring/aot.factories
Labels: task

#2168 Use both hostname and IP address to find ssh configuration in config-server
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/FileBasedSshSessionFactory.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactoryTest.java
Labels: bug

#2175 Sets default connection attempt to 1 in config-server
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactoryTest.java
Labels: task

#2179 Fix indentation. Document AOT and native support.
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: documentation
