Repository spring-cloud/spring-cloud-config, pull requests merged in 2022-12, with the labels that each got.

#2198 Bumping JGit to 6.4
  spring-cloud-config-dependencies/pom.xml
Labels: dependencies

#2196 Make SQL Without Profile Optional
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepositoryTests.java
Labels: in progress

#2200 Make SQL Without Profile Adaptive
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/resources/data-jdbc.sql
Labels: bug
