Repository spring-cloud/spring-cloud-config, pull requests merged in 2022-09, with the labels that each got.

#2144 fix micrometer dependency changes
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/DocumentedConfigObservation.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/ObservationEnvironmentRepositoryObservationConvention.java
Labels: task

#2150 Support files with yaml extension in S3
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepositoryTests.java
Labels: bug

#2147 Exact match of branch names in JGitEnvironmentRepository - Fixes gh-2133
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/bar.yml
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/COMMIT_EDITMSG
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/HEAD
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/config
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/description
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/index
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/logs/HEAD
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/logs/refs/heads/feature/foo
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/logs/refs/heads/master
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/08/eb9e67a7225c302e3906a63cb9544e619fc804
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/0d/706a8f14e7ec2b9abf99c603f3f5467d2d38ff
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/54/8298f39d0c5a84a1ada7a2b03ef54aad1fffa2
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/5c/19df95639519f2286fc6d39182f271ee8c0b6b
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/6e/067728a52e959f60788121b4046e5b27793e61
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/7a/9804f8901709bdcf794c553805d5bc5188f821
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/91/5bd24aaf815120f2755ef4fc66404f5d37b383
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/ae/c5d43644133593483b7c243f851606aa2c0128
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/objects/fa/c65b3a4678430e2b86e3b28510b37c5a7942a7
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/refs/heads/feature/foo
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/refs/heads/master
  spring-cloud-config-server/src/test/resources/branch-with-slash-repo/git/refs/tags/foo
Labels: waiting for feedback

#2132 Simplify regex in EnvironmentController
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/EnvironmentControllerTests.java
Labels: task
