Repository spring-cloud/spring-cloud-config, pull requests merged in 2022-03, with the labels that each got.

#1946 Add support for multiple-url-strategy configuration for clients.
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigClientPropertiesTests.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoaderTests.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocatorTests.java
Labels: in progress

#2056 [config-server] Allow specification of down health status
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerHealthIndicator.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/config/ConfigServerHealthIndicatorTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfigurationTests.java
Labels: enhancement

#2059 Allow for hyphen in path but exclude periods.
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/EnvironmentControllerIntegrationTests.java
Labels: in progress

#2065 Simplify encryption autoconfig
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/DefaultTextEncryptionAutoConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EncryptionAutoConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/RsaEncryptionAutoConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java
  spring-cloud-config-server/src/main/resources/META-INF/spring.factories
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/BootstrapConfigServerIntegrationTests.java
Labels: bug

#2073 Use path to key property in SpringVaultEnvironmentRepository
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryTests.java
Labels: in progress
