Repository spring-cloud/spring-cloud-config, pull requests merged in 2022-11, with the labels that each got.

#2177 Support application name with dashes on RefreshRemoteApplicationEvent
  spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java
  spring-cloud-config-monitor/src/test/java/org/springframework/cloud/config/monitor/PropertyPathEndpointTests.java
Labels: bug

#2172 Fix tests fails on Windows caused by newline format
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/resource/ResourceControllerTests.java
Labels: task

#2079 docs(-): git.timeout default is 5
  docs/src/main/asciidoc/spring-cloud-config.adoc
Labels: documentation

#2162 Update logging message on MultipleJGitEnvironmentRepository, JGitEnvironmentRepository
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MultipleJGitEnvironmentRepository.java
Labels: waiting for feedback

#2191 Fix getLocations that was ignoring failOnCompositeError flag
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CompositeEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SearchPathCompositeEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/CompositeEnvironmentRepositoryTests.java
Labels: in progress
