Repository spring-cloud/spring-cloud-config, pull requests merged in 2023-05, with the labels that each got.

#2227 Reenable AwsIntegrationTest On Main
  pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/AwsS3IntegrationTests.java
Labels: task

#2260 Support for profile specific config data loading
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolver.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataResource.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataCustomizationIntegrationTests.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoaderTests.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolverTests.java
Labels: in progress

#2263 Better parsing of connection factory urls
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/HttpClientConfigurableHttpConnectionFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/HttpClientConfigurableHttpConnectionFactoryTest.java
Labels: waiting-for-triage

#2247 fix issue #2245, related to #385
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java
Labels: in progress

#2253 fix: transmit data from spring cloud config server controller to getEncryptor
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/encryption/EncryptionControllerTests.java
Labels: waiting for feedback
