Repository spring-cloud/spring-cloud-config, pull requests merged in 2023-02, with the labels that each got.

#2219 Fix AWS S3 ResourceController support
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/SearchPathLocator.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/PathUtils.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/resource/GenericResourceRepositoryTests.java
Labels: waiting-for-triage

#2225 Add integration test for S3 environment repository
  spring-cloud-config-dependencies/pom.xml
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/AwsS3IntegrationTests.java
Labels: task

#2223 Fix variable name in AwsS3EnvironmentRepository.java for readability
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepository.java
Labels: task

#2057 Do not hide various errors under "connect timeout" message
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java
Labels: task

#1977 Let config client fail before bean creation
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientAutoConfiguration.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-sample/src/test/java/sample/ApplicationFailFastTests.java
Labels: in progress

#1944 Fixes gh-1940.
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/resource/ResourceControllerIntegrationTests.java
Labels: in progress

#2233 Pr 2104 polish
  docs/src/main/asciidoc/spring-cloud-config.adoc
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentRepositoryTests.java
Labels: enhancement
