Repository spring-cloud/spring-cloud-config, pull requests merged in 2023-06, with the labels that each got.

#2275 Recreate ConfigClientProperties every time we load config data
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolver.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigClientConfigDataLoaderTest.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/DiscoveryClientConfigDataConfigurationTests.java
  spring-cloud-config-client/src/test/resources/applicationname.yaml
Labels: waiting-for-triage

#2269 Pass binder to ConfigServerInstanceProvider
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolver.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerInstanceProvider.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/DiscoveryClientConfigDataConfigurationNoRetryTests.java
Labels: bug

#2285 Create a bean for ResourceControllerAdvice
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerMvcConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceControllerAdvice.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/resource/ResourceControllerIntegrationTests.java
Labels: bug

#2286 Removes duplicate bean definition in ResourceControllerIntegrationTests
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/resource/ResourceControllerIntegrationTests.java
Labels: task

#2288 Configures SshSessionFactory only if there is at least one git uri with ssh scheme
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/FileBasedSshTransportConfigCallback.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/PropertiesBasedSshTransportConfigCallback.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/TransportConfigurationIntegrationTests.java
Labels: in progress

#2290 Removes unnecessary @RunWith annotations
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/TransportConfigurationIntegrationTests.java
Labels: task

#2278 Implement a better equals and hashcode method ConfigServerConfigDataResource
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataResource.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigClientConfigDataLoaderTest.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataResourceTests.java
Labels: bug

#2292 Revert changes to adding profile specific logic
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataCustomizationIntegrationTests.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoaderTests.java
Labels: in progress
