Repository spring-cloud/spring-cloud-config, pull requests merged in 2024-03, with the labels that each got.

#2389 docs: add Custom Environment Repositories and update config sharing
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/server/environment-repository/custom-enviroment-repository.adoc
  docs/modules/ROOT/pages/server/environment-repository/sharing-configuration-with-all-applications.adoc
Labels: documentation

#2393 fix: allow negative value for jgit environment to disable refresh
  docs/modules/ROOT/pages/server/environment-repository/git-backend.adoc
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryTests.java
Labels: enhancement, in progress

#2394 fix: configure ssh connect timeout value
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/FileBasedSshSessionFactory.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/ssh/FileBasedSshSessionFactoryTest.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/ssh/PropertyBasedSshSessionFactoryTest.java
Labels: enhancement

#2396 docs: update git backend docs to include ssh connection timeout
  docs/modules/ROOT/pages/server/environment-repository/git-backend.adoc
Labels: documentation
