Repository spring-cloud/spring-cloud-config, pull requests merged in 2024-09, with the labels that each got.

#2458 Fixes the order of profiles and application names in CredhubEnvironmentRepository
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepositoryTests.java
Labels: bug

#2459 Cleanup VaultEnvironmentRepository unit tests
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryTests.java
Labels: task

#2519 Makes default-label in CredhubEnvironmentRepository configurable
  docs/modules/ROOT/pages/server/environment-repository/credhub-backend.adoc
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepositoryTests.java
Labels: enhancement

#2521 Enables defining a base path for CredHub credentials
  docs/modules/ROOT/pages/server/environment-repository/credhub-backend.adoc
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepositoryTests.java
Labels: enhancement

#2456 feat: native support for retry template factory
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientAutoConfiguration.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/aot/ConfigClientHints.java
  spring-cloud-config-client/src/main/resources/META-INF/spring/aot.factories
Labels: bug

#2543 Update tls tests to add test that tests creating a truststore without a keystore
  spring-cloud-config-client-tls-tests/src/test/java/org/springframework/cloud/config/client/tls/ConfigClientTlsTests.java
Labels: waiting-for-triage
