Repository spring-cloud/spring-cloud-config, pull requests merged in 2024-10, with the labels that each got.

#2455 Support multiple labels in JdbcEnvironmentRepository
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/resources/data-jdbc.sql
Labels: waiting-for-triage

#2567 Initial implementation to support multiple labels with aws secret manager
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/AwsSecretsManagerEnvironmentRepositoryTests.java
Labels: waiting-for-triage

#2564 Initial support for multiple labels for AWS S3
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AwsS3EnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/AwsS3IntegrationTests.java
Labels: waiting-for-triage

#2561 Initial implementation to support multiple labels in SVN and Git EnvironmentRepos
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractScmEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/CompositeIntegrationTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/SVNKitEnvironmentRepositoryTests.java
Labels: waiting-for-triage

#2568 Initial implementation to support multiple labels for credhub
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepositoryTests.java
Labels: waiting-for-triage

#2390 feat(config-server): add MongoDB environment repository support
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/server/environment-repository/mongo-backend.adoc
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MongoDbEnvironmentProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MongoDbEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/MongoDbEnvironmentRepositoryFactory.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/MongoDbEnvironmentRepositoryConfigurationTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/MongoDbEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/resources/data-mongo.json
Labels: enhancement

#2440 feat: resource charset support
  .gitattributes
  docs/modules/ROOT/pages/client.adoc
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientProperties.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/resource/ResourceControllerTests.java
  spring-cloud-config-server/src/test/resources/test/dev/foo_enc
  spring-cloud-config-server/src/test/resources/test/dev/foo_enc.properties
Labels: waiting for feedback

#2581 Default-label in CredhubEnviornmentRepository should be used only if label is not provided
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepository.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/CredhubEnvironmentRepositoryTests.java
Labels: bug

#2460 Uses label when searching secrets in [Spring]VaultEnvironmentRepository
  docs/modules/ROOT/pages/server/environment-repository/vault-backend.adoc
  spring-cloud-config-sample/src/test/java/sample/ConfigDataOrderingVaultIntegrationTests.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractVaultEnvironmentRepository.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/VaultEnvironmentProperties.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/VaultEnvironmentRepositoryTests.java
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/environment/vault/SpringVaultEnvironmentRepositoryTests.java
Labels: bug

#2585 Refactor and cleanup AbstractScmEnvironmentRepository
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractScmEnvironmentRepository.java
Labels: task

#2596 Fixes checkstyle issues
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/proxy/ProxyHostProperties.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/GitSkipSslValidationCredentialsProvider.java
Labels: task

#2545 fix: use withLogger of RetryTemplateBuilder to avoid reflections
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/RetryTemplateFactory.java
  spring-cloud-config-dependencies/pom.xml
Labels: enhancement

#2613 Only ignore profile activation and inclusion if the property source is profile specific
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java
  spring-cloud-config-client/src/test/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoaderTests.java
Labels: bug
