Repository spring-cloud/spring-cloud-config, pull requests merged in 2024-05, with the labels that each got.

#2412 Fix composite environment aot and native image generation
  spring-cloud-config-server/pom.xml
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/aot/CompositeEnvironmentBeanFactoryInitializationAotProcessor.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/composite/CompositeUtils.java
  spring-cloud-config-server/src/main/resources/META-INF/spring/aot.factories
  spring-cloud-config-server/src/test/java/org/springframework/cloud/config/server/aot/CompositeEnvironmentBeanFactoryInitializationAotProcessorTests.java
Labels: bug

#2416 docs: add documentation for decrypting Vault secrets in property sources
  docs/modules/ROOT/pages/server/environment-repository/vault-backend.adoc
Labels: documentation

#2418 Polishing
  spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientRequestTemplateFactory.java
  spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/encryption/EncryptionController.java
Labels: task
